### ISSUE TITLE
Error when training

### ISSUE THREAD

**Issue by zyntax9999** [yusuketomoto/chainer-fast-neuralstyle#22]
I get a error when trying to train:

`
python train.py -s ~/chainer-fast-neuralstyle/styles/oilp.jpg -d ~/chainer-fast-neuralstyle/dataset/train2014/ --gpu 0`

num traning images: 82783
82783 iterations, 2 epochs
epoch 0
Traceback (most recent call last):
  File "train.py", line 122, in <module>
    x[j] = load_image(imagepaths[i*batchsize + j], image_size)
  File "train.py", line 21, in load_image
    return xp.asarray(image, dtype=np.float32).transpose(2, 0, 1)
  File "/usr/local/lib/python2.7/dist-packages/cupy/creation/from_data.py", line 47, in asarray
    return cupy.array(a, dtype=dtype, copy=False)
  File "/usr/local/lib/python2.7/dist-packages/cupy/creation/from_data.py", line 27, in array
    return core.array(obj, dtype, copy, ndmin)
  File "cupy/core/core.pyx", line 1400, in cupy.core.core.array (cupy/core/core.cpp:49505)
  File "cupy/core/core.pyx", line 1414, in cupy.core.core.array (cupy/core/core.cpp:49121)
  File "/usr/lib/python2.7/dist-packages/PIL/Image.py", line 528, in __getattr__
    raise AttributeError(name)
AttributeError: __float__

**Comment by zyntax9999** [comment]
Anyone who can help me fix this ^^

**Comment by zyntax9999** [comment]
Doing `sudo git install Pillow --upgrade` fixed this for me :-)

**Comment by ttoinou** [comment]
What is your setup ? How did you install chainer with cuda ?
I don't understand the error, it looks like cuda is calling PIL it's weird

**Comment by ttoinou** [comment]
Ah ok the callback chain was weird though
