### ISSUE TITLE
Cuda BLAS error on generate.py with custom model

### ISSUE THREAD

**Issue by jamiis** [yusuketomoto/chainer-fast-neuralstyle#34]
I trained my own model called `models/beach.model` but I cannot use it thus far:
```
$ python generate.py content/condon-01.jpg -m models/beach.model -o output/condon-01-illusion.jpg
/home/jamis/.local/lib/python2.7/site-packages/chainer/cuda.py:87: UserWarning: cuDNN is not enabled.
Please reinstall chainer after you install cudnn
(see https://github.com/pfnet/chainer#installation).
  'cuDNN is not enabled.\n'
Traceback (most recent call last):
  File "generate.py", line 30, in <module>
    y = model(x)
  File "/home/jamis/src/chainer-fast-neuralstyle/net.py", line 55, in __call__
    h = self.b1(F.elu(self.c1(x)), test=test)
  File "/home/jamis/.local/lib/python2.7/site-packages/chainer/links/connection/convolution_2d.py", line 82, in __call__
    x, self.W, self.b, self.stride, self.pad, self.use_cudnn)
  File "/home/jamis/.local/lib/python2.7/site-packages/chainer/functions/connection/convolution_2d.py", line 316, in convolution_2d
    return func(x, W, b)
  File "/home/jamis/.local/lib/python2.7/site-packages/chainer/function.py", line 130, in __call__
    outputs = self.forward(in_data)
  File "/home/jamis/.local/lib/python2.7/site-packages/chainer/function.py", line 234, in forward
    return self.forward_gpu(inputs)
  File "/home/jamis/.local/lib/python2.7/site-packages/chainer/functions/connection/convolution_2d.py", line 137, in forward_gpu
    y_mats[i] = W_mat.dot(col_mats[i])
  File "cupy/core/core.pyx", line 1109, in cupy.core.core.ndarray.dot (cupy/core/core.cpp:22101)
  File "cupy/core/core.pyx", line 1876, in cupy.core.core.dot (cupy/core/core.cpp:55022)
  File "cupy/core/core.pyx", line 1958, in cupy.core.core.tensordot_core (cupy/core/core.cpp:56307)
  File "cupy/cuda/device.pyx", line 20, in cupy.cuda.device.get_cublas_handle (cupy/cuda/device.cpp:1234)
  File "cupy/cuda/device.pyx", line 109, in cupy.cuda.device.Device.cublas_handle.__get__ (cupy/cuda/device.cpp:2443)
  File "cupy/cuda/device.pyx", line 110, in cupy.cuda.device.Device.cublas_handle.__get__ (cupy/cuda/device.cpp:2381)
  File "cupy/cuda/cublas.pyx", line 120, in cupy.cuda.cublas.create (cupy/cuda/cublas.cpp:1351)
  File "cupy/cuda/cublas.pyx", line 110, in cupy.cuda.cublas.check_status (cupy/cuda/cublas.cpp:1236)
cupy.cuda.cublas.CUBLASError: CUBLAS_STATUS_NOT_INITIALIZED
```
Also, as mentioned in another issue, I am being told that I have not installed cuDNN but I believe I have:
```
ldconfig -p | grep cudnn
        libcudnn.so.5 (libc6,x86-64) => /usr/local/cuda/lib64/libcudnn.so.5
        libcudnn.so.4 (libc6,x86-64) => /usr/local/cuda/lib64/libcudnn.so.4
```
I reinstalled chainer multiple times. Do I need to restart or something? That seems a bit over the top: Cuda is already in my PATH and all the other environment vars required.

I am running on a Titan X and have 2 of them in my machine:
```
$ nvidia-smi
Tue Aug  9 11:48:30 2016
+------------------------------------------------------+
| NVIDIA-SMI 361.42     Driver Version: 361.42         |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce GTX TIT...  Off  | 0000:6D:00.0     Off |                  N/A |
| 22%   32C    P8    14W / 250W |     24MiB / 12287MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   1  GeForce GTX TIT...  Off  | 0000:6E:00.0     Off |                  N/A |
| 22%   43C    P8    31W / 250W |    911MiB / 12285MiB |     29%      Default |
+-------------------------------+----------------------+----------------------+

+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID  Type  Process name                               Usage      |
|=============================================================================|
|    1      4207    G   /usr/lib/xorg/Xorg                             332MiB |
|    1      5307    G   compiz                                         461MiB |
|    1     10126    G   ...inFlow --disable-features=DocumentWriteEv    87MiB |
+-----------------------------------------------------------------------------+
```

**Comment by jamiis** [comment]
Also, it looks like I have cuBLAS installed as well. 
```
$ ldconfig -p | grep blas
        libnvblas.so.7.5 (libc6,x86-64) => /usr/local/cuda/lib64/libnvblas.so.7.5
        libnvblas.so.7.5 (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libnvblas.so.7.5
        libnvblas.so (libc6,x86-64) => /usr/local/cuda/lib64/libnvblas.so
        libnvblas.so (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libnvblas.so
        libgslcblas.so.0 (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libgslcblas.so.0
        libcublas.so.7.5 (libc6,x86-64) => /usr/local/cuda/lib64/libcublas.so.7.5
        libcublas.so.7.5 (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libcublas.so.7.5
        libcublas.so (libc6,x86-64) => /usr/local/cuda/lib64/libcublas.so
        libcublas.so (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libcublas.so
        libblas.so.3 (libc6,x86-64) => /usr/lib/libblas.so.3
```
I believe it comes with Cuda 7.5. Maybe my path is messed up or something? I have a feeling this could be connected with not detecting cuDNN. I have verified that both `train.py` and `generate.py` run on the GPU.

**Comment by jamiis** [comment]
Huh, upgrading to chainer 1.13 fixed it even though that release was only 16 hours ago: https://github.com/pfnet/chainer/commit/aa7bb87ce86ae058422e2507e8f1ba4d89a85a1f
```
$ pip install --user --upgrade chainer
Collecting chainer
  Downloading chainer-1.13.0.tar.gz (1.0MB)
    100% |████████████████████████████████| 1.0MB 857kB/s
Requirement already up-to-date: filelock in /home/jamis/.local/lib/python2.7/site-packages (from chainer)
Requirement already up-to-date: nose in /home/jamis/.local/lib/python2.7/site-packages (from chainer)
Requirement already up-to-date: numpy>=1.9.0 in /home/jamis/.local/lib/python2.7/site-packages (from chainer)
Requirement already up-to-date: protobuf in /home/jamis/.local/lib/python2.7/site-packages (from chainer)
Requirement already up-to-date: six>=1.9.0 in /usr/lib/python2.7/dist-packages (from chainer)
Requirement already up-to-date: setuptools in /home/jamis/.local/lib/python2.7/site-packages (from protobuf->chainer)
Building wheels for collected packages: chainer
  Running setup.py bdist_wheel for chainer ... \done
  Stored in directory: /home/jamis/.cache/pip/wheels/a6/5f/c2/f87d72d48c6b3e0a69b8a700c99a69240a4f364e3ff007d872
Successfully built chainer
Installing collected packages: chainer
  Found existing installation: chainer 1.12.0
    Uninstalling chainer-1.12.0:
      Successfully uninstalled chainer-1.12.0
Successfully installed chainer-1.13.0
```
Not sure what caused this. I'll leave this here for anyone who runs into the same problem.

**Comment by yusuketomoto** [comment]
I hope this would be some of your help:
https://github.com/pfnet/chainer/issues/1241
