### ISSUE TITLE
python train.py -s sample_images/style_1.png -d train2014

### ISSUE THREAD

**Issue by azheng333** [yusuketomoto/chainer-fast-neuralstyle#40]
num traning images: 82783
82783 iterations, 2 epochs
epoch 0
Traceback (most recent call last):
  File "train.py", line 124, in <module>
    x[j] = load_image(imagepaths[i*batchsize + j], image_size)
  File "train.py", line 23, in load_image
    return xp.asarray(image, dtype=np.float64).transpose(2, 0, 1)
  File "/usr/lib64/python2.7/site-packages/numpy/core/numeric.py", line 482, in asarray
    return array(a, dtype, copy=False, order=order)
  File "/usr/lib64/python2.7/site-packages/PIL/Image.py", line 514, in __getattr__
    raise AttributeError(name)
AttributeError: __float__

**Comment by shun-sa** [comment]
I also had same problem.
In conclusion, modify `train.py` line 23 
`image = image.crop((int((w-size)*0.5), int((h-size)*0.5), int((w+size)*0.5), int((h+size)*0.5)))
`

This problem seems to occur when crop by real number.

**Comment by azheng333** [comment]
yes, thanks
