### ISSUE TITLE
cupy/cuda/cudnn error: integer required

### ISSUE THREAD

**Issue by tisawe** [yusuketomoto/chainer-fast-neuralstyle#63]
My Ubuntu 14 environment is set up properly. I can run this program using the CPU but I get this error when I choose to use my CUDNN compatible GPU: 
Traceback (most recent call last):
File "generate.py", line 31, in 
y = model(x)
File "/home/user/chainer-fast-neuralstyle-master/net.py", line 55, in call
h = self.b1(F.elu(self.c1(x)), test=test)
File "/usr/local/lib/python2.7/dist-packages/chainer-1.16.0-py2.7-linux-x86_64.egg/chainer/links/connection/convolution_2d.py", line 101, in call
x, self.W, self.b, self.stride, self.pad, self.use_cudnn)
File "/usr/local/lib/python2.7/dist-packages/chainer-1.16.0-py2.7-linux-x86_64.egg/chainer/functions/connection/convolution_2d.py", line 318, in convolution_2d
return func(x, W, b)
File "/usr/local/lib/python2.7/dist-packages/chainer-1.16.0-py2.7-linux-x86_64.egg/chainer/function.py", line 197, in call
outputs = self.forward(in_data)
File "/usr/local/lib/python2.7/dist-packages/chainer-1.16.0-py2.7-linux-x86_64.egg/chainer/function.py", line 309, in forward
return self.forward_gpu(inputs)
File "/usr/local/lib/python2.7/dist-packages/chainer-1.16.0-py2.7-linux-x86_64.egg/chainer/functions/connection/convolution_2d.py", line 103, in forward_gpu
(self.ph, self.pw), (self.sy, self.sx), x.dtype)
File "/usr/local/lib/python2.7/dist-packages/cupy-1.0.0-py2.7-linux-x86_64.egg/cupy/cudnn.py", line 101, in create_convolution_descriptor
desc.value, pad[0], pad[1], stride[0], stride[1], 1, 1, mode)
File "cupy/cuda/cudnn.pyx", line 348, in cupy.cuda.cudnn.setConvolution2dDescriptor (cupy/cuda/cudnn.cpp:3986)
TypeError: an integer is required

**Comment by elianalien** [comment]
might be the chainer lib you're using isn't compatible with cuDNN installed. 
try downgrading the chainer lib. I'm using cudNN-8.0 v6 so that i'm using chainner 1.22.0
`pip install 'chainer==1.22.0'`
