### ISSUE TITLE
bigger image size

### ISSUE THREAD

**Issue by artnose** [yusuketomoto/chainer-fast-neuralstyle#66]
I get this error 
epoch 0
Traceback (most recent call last):
  File "train.py", line 135, in <module>
    L_feat = lambda_f * F.mean_squared_error(Variable(feature[2].data), feature_hat[2]) # compute for only the output of
 layer conv3_3
  File "/usr/lib64/python2.7/site-packages/chainer/functions/loss/mean_squared_error.py", line 44, in mean_squared_error
    return MeanSquaredError()(x0, x1)
  File "/usr/lib64/python2.7/site-packages/chainer/function.py", line 190, in __call__
    self._check_data_type_forward(in_data)
  File "/usr/lib64/python2.7/site-packages/chainer/function.py", line 273, in _check_data_type_forward
    type_check.InvalidType(e.expect, e.actual, msg=msg), None)
  File "/usr/lib/python2.7/site-packages/six.py", line 718, in raise_from
    raise value
chainer.utils.type_check.InvalidType:
Invalid operation is performed in: MeanSquaredError (Forward)

Expect: in_types[0].shape == in_types[1].shape
Actual: (1, 256, 119, 119) != (1, 256, 118, 118)

what are the restrictions on image size?

**Comment by 6o6o** [comment]
Chainer is not perfect in its operations. The resulting convolved image will not necessarily match the size of the source image, even if you specify the right padding to compensate for kernel size. That's why it is recommended to use sizes, which are multiples of 16, 8, or 4 at least.

**Comment by 6o6o** [comment]
Chainer is not perfect in its operations. The resulting convolved image will not necessarily match the size of the source image, even if you specify the right padding to compensate for kernel size. That's why it is recommended to use sizes, which are multiples of 16, 8, or 4 at least.

If you really need to use 118, you can explicitly pass `outsize` argument to `Deconvolution2D` upon initialization, but it makes the operation less convenient.
