### ISSUE TITLE
How to train the net work

### ISSUE THREAD

**Issue by gecong** [yusuketomoto/chainer-fast-neuralstyle#67]
Can anyone provide details about how to train the net work? I went to MSCOCO and downloaded the package. Do I need to do anything more before I run the train.py?

**Comment by HighKo** [comment]
You have to extract them into a sub-folder named dataset or provide the path directly.

**Comment by shridharkini6** [comment]
what could be the potential problem for this error during training.
My input images are of 256x256 jpg images
Traceback (most recent call last):
  File "train.py", line 117, in <module>
    x[j] = load_image(imagepaths[i*batchsize + j], image_size)
  File "train.py", line 21, in load_image
    return xp.asarray(image, dtype=np.float32).transpose(2, 0, 1)
  File "/home/ubuntu/1000lookz_ocr_app/.virtualenvs/venv1/lib/python2.7/site-packages/cupy/creation/from_data.py", line 47, in asarray
    return cupy.array(a, dtype=dtype, copy=False)
  File "/home/ubuntu/1000lookz_ocr_app/.virtualenvs/venv1/lib/python2.7/site-packages/cupy/creation/from_data.py", line 27, in array
    return core.array(obj, dtype, copy, ndmin)
  File "cupy/core/core.pyx", line 1479, in cupy.core.core.array (cupy/core/core.cpp:50421)
  File "cupy/core/core.pyx", line 1493, in cupy.core.core.array (cupy/core/core.cpp:50031)
TypeError: float() argument must be a string or a number

**Comment by shridharkini6** [comment]
anyone has suggestion for this
